services:
  # Service Redis pour le cache
  redis:
    image: redis:7-alpine
    container_name: folio-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    networks:
      - folio-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      timeout: 3s
      retries: 5

  # Service Backend (API)
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: folio-backend
    restart: unless-stopped
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
      - PORT=3001
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - GITHUB_TOKEN=${GITHUB_TOKEN}
    volumes:
      - ./backend/public:/app/public
    networks:
      - folio-network
    depends_on:
      redis:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3001/health"]
      timeout: 3s
      retries: 5
      start_period: 40s

  # Service Frontend (Interface utilisateur)
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: folio-frontend
    restart: unless-stopped
    ports:
      - "8080:80"
    networks:
      - folio-network
    depends_on:
      backend:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:80"]
      timeout: 3s
      retries: 5

networks:
  folio-network:
    driver: bridge

volumes:
  redis_data:
    driver: local
